### ISSUE TITLE
is that possible to add some features?

### ISSUE THREAD

**Issue by suriyaJaay** [rajatsehgal/gmailer#1]
is that possible for you create following things?

front end 
send mail to selected contacts like if  want to send  same mail to 10 contacts out of 50 contacts from the db mysql/mongo 

thank you

**Comment by rajatsehgal** [comment]
This module is meant to be a light-weight backend utility to help send emails using a gmail account. You're free to hookup any front end that you want to utilize this API in your node server. I don't plan to add any more features to this module.
